LDpred2.R uses external ld matrix (partial fix for #108)
comorment/containers pull request #109
Opened 2022-12-09 14:21 UTC by ofrei

Fixes first half of #108

Changes proposed in this pull request:

- remove LD matrix computation from LDpred2.R script
- instead, load reference data submitted to https://github.com/comorment/ldpred2_ref repository. For now the path to the reference was hard-coded (fell free to fix, or I can fix later)
- allow to read subset of chromosomes using ``--chr2use`` flag
- overlap the set of SNPs from (1) sumstats file (2) genotype (3) LD reference. Use [snp_match](https://privefl.github.io/bigsnpr/reference/snp_match.html) function to perform this logic. Prefer merging on CHR:BP:A1:A2, give user a new ``--merge-by-rsid`` option to perform merging on rs# (SNP marker name). Test ``snp_match`` with a new unit-test, ``tests/extras/bigsnpr.R`` (the test passes)
- implement new dataset (see ``reference/examples/ldpred2`` folder), which allows to test how well ``LDpred2`` matches SNPs from sumstats, genotypes and LD reference. The tool also runs very fast on that dataset because it only includes chr21 and chr22.
- remove run_ldpred2.sh; usage example integrated into README.md

## Before submitting

- [x] I've read and followed all steps in the [Making a pull request](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#making-a-pull-request)
    section of the `CONTRIBUTING` docs.
- [x] I've updated or added any relevant docstrings following the syntax described in the
    [Writing docstrings](https://github.com/comorment/containers/blob/main/CONTRIBUTING.md#writing-docstrings) section of the `CONTRIBUTING` docs.
- [ ] If this PR fixes a bug, I've added a test that will fail without my fix.
- [x] If this PR adds a new feature, I've added tests that sufficiently cover my new functionality.

2022-12-09 14:29 UTC, ofrei commented
I'll fix Flake8 linter errors later today. The LD reference files are stil being uploaded to https://github.com/comorment/ldpred2_ref . Apart from this this PR is ready for review.

2022-12-12 10:11 UTC, ofrei commented
@deepchocolate @espenhgn I pushed few more changes, that's would be all I wanted to implement for ldpred2.R. Is it fine to merge? I'd like to ask our colleagues at CoMorMent to have a look before the meeting tomorrow.

@deepchocolate what do you think about adding --geno-file, --sumstats  and --out as named arguments, rather than using them as positional arguments? I generally prefer named arguments over positional arguments, also for those arguments that are required. To me this is more readable and intuitive as one doesn't need to know that order in which positional arguments must be provided. Also it's fine to reorder without breaking backwards compatibility. Finally, with --chr2use argument with ``narg=Inf`` the behaviour is non-intuitive if ``--chr2use`` is the last argument before positional arguments, e.g. ``... --chr2use 21 22 $genoFile $sumstatsFile $outFile``. In this situation  R parser doesn't have a way to know that there are only 2 arguments for --chr2use, the other three are positional. The command fails but  that's really hard for the user to investigate.

2022-12-12 10:33 UTC, deepchocolate commented
> @deepchocolate @espenhgn I pushed few more changes, that's would be all I wanted to implement for ldpred2.R. Is it fine to merge? I'd like to ask our colleagues at CoMorMent to have a look before the meeting tomorrow.
> 

I'm looking at it now, I'll approve today, just checking if I need to do some changes somewhere. If there are any I'll put them in a separate branch

> @deepchocolate what do you think about adding --geno-file, --sumstats and --out as named arguments, rather than using them as positional arguments? I generally prefer named arguments over positional arguments, also for those arguments that are required. To me this is more readable and intuitive as one doesn't need to know that order in which positional arguments must be provided. Also it's fine to reorder without breaking backwards compatibility. Finally, with --chr2use argument with `narg=Inf` the behaviour is non-intuitive if `--chr2use` is the last argument before positional arguments, e.g. `... --chr2use 21 22 $genoFile $sumstatsFile $outFile`. In this situation R parser doesn't have a way to know that there are only 2 arguments for --chr2use, the other three are positional. The command fails but that's really hard for the user to investigate.

That's fine by me, good point!  Also good to harmonize arguments to gwas.py, didn't think about that as I usually try to prefix the arguments after what they specify (`--file-...`).

2022-12-12 11:20 UTC, ofrei commented
@deepchocolate I agree about ``--file-``, this sounds good idea to me, and currently this is also inconsistent in gwas.py (e.g. --sumstats also points to the file same as --geno-file, but for no good reason only one of them has ``-file``). I suggest for now we keep things consistent with ``gwas.py``, discuss the ideal names when there is more time, and change naming for in a later release.

2022-12-12 12:26 UTC, espenhgn requested changes

2022-12-12 12:38 UTC, ofrei commented on usecases/LDpred2/run_ldpred2_slurm.job
> +export SINGULARITY_BIND=$REFERENCE:/REF,${LDPRED2_REF}:/ldpred2_ref
Yes, that's correct. I suggest all comorment repos (http://github.com/comorment/containers, https://github.com/comorment/ldpred2_ref etc) are cloned to one root-level folder  which is referred to as $COMORMENT.

2022-12-12 12:42 UTC, ofrei commented on usecases/LDpred2/README.md
> +## Running LDpred2 analysis - synthetic example (chr21 and chr22)
These files together take around 250 MB, perhaps too big for a demo. I suggest we keep them in ``ldpred2_ref`` repo for now, and later we can generate our own small-scale demo LD example using ``calculateSnpCorrelation.R`` script that @deepchocolate will develop as part of #108

2022-12-12 12:42 UTC, espenhgn commented on usecases/LDpred2/README.md
> +## Running LDpred2 analysis - synthetic example (chr21 and chr22)
I should add: I could run both the infinitesimal and auto models without issues (chr 21-22). At least the p/h2 vs. iteration plots now make sense.

2022-12-12 12:51 UTC, deepchocolate commented on usecases/LDpred2/run_ldpred2_slurm.job
> +export SINGULARITY_BIND=$REFERENCE:/REF,${LDPRED2_REF}:/ldpred2_ref
Ah, I see!

2022-12-12 12:54 UTC, ofrei commented on usecases/LDpred2/ldpred2.R
> +library(stringr)
:+1: will fix

2022-12-12 13:02 UTC, ofrei commented on usecases/LDpred2/ldpred2_simulations.ipynb
> +    "bfile = '/home/oleksanf/github/comorment/magma/reference/magma/g1000_eur/g1000_eur'\n",
Added brief description on top, that's for sure a good idea.

2022-12-12 13:02 UTC, ofrei commented on usecases/LDpred2/ldpred2_simulations.ipynb
> +    "bfile = '/home/oleksanf/github/comorment/magma/reference/magma/g1000_eur/g1000_eur'\n",
Reproducing from within container is also good, but I haven't tested it yet.

2022-12-12 13:03 UTC, ofrei commented on usecases/LDpred2/README.md
> +## Running LDpred2 analysis - synthetic example (chr21 and chr22)
Great! The examples are swapped now, so chr21-22 is described first, followed by full example

2022-12-12 14:49 UTC, ofrei commented
I rebuilt r.sif container including ``stringr`` library, and fix other thing we discussed with @espenhgn 
Also there is now a note on handling missing genotypes: https://github.com/comorment/containers/tree/of_ldpred2/usecases/LDpred2#handling-missing-genotypes
OK to merge?

2022-12-12 15:24 UTC, deepchocolate approved these changes
Great!

2022-12-12 18:07 UTC, merged